### PR TITLE
Show the LDAP configuration status in the configuration chooser

### PR DESCRIPTION
**Pull request by jvillafanez**
Original PR: https://github.com/owncloud/core/pull/25409

**NOTE** The original PR states that some changes are needed. Check, test and fix before merging this.

### CODE REVIEW

**Comment by PVince81** [comment]
@jvillafanez finish or close ?

conflicts detected

**Comment by jvillafanez** [comment]
I guess this depends on the level of interest. Maybe @pmaier1 or @felixboehm can decide what to do with this.
It shouldn't be difficult to fix the PR.

**Comment by pmaier1** [comment]
> I guess this depends on the level of interest. Maybe @pmaier1 or @felixboehm can decide what to do with this.
It shouldn't be difficult to fix the PR.

If this is almost done, then would of course be nice to merge. Can you take care @jvillafanez ?

**Comment by jvillafanez** [comment]
Rebased. Needs testing though.

**Comment by mmattel** [comment]
@jvillafanez @pmaier1 @PVince81 any update on that one?

**Comment by PVince81** [comment]
@jvillafanez please rebase again and give instructions for @davitol to confirm this works (considering that there are no unit tests for JS side)

**Comment by PVince81** [comment]
also wondering if we should just close in favor of new wizard. @butonic thoughts ?

**Comment by PVince81** [comment]
I'm closing this. let's better invest the time in the new wizard

**Pull request closed without merging**
