### PR TITLE
autodetect 'ipauniqueid' in Connection as well

### PR DESCRIPTION
**Pull request by butonic**
fixes https://github.com/owncloud/user_ldap/issues/33

### CODE REVIEW

**Comment by butonic** [comment]
@xelez can you test?

**Comment by xelez** [comment]
@butonic Tested, works. But I think at least a comment near both arrays, mentioning that you have change the other array is needed.

**Comment by xelez** [comment]
Is it going to be merged?

**Comment by PVince81** [comment]
> that you have change the other array is needed so that this error

@xelez not sure what you mean with your comment.

@jvillafanez is this PR acceptable ?

**Comment by butonic** [comment]
IMO for now this makes sense ... the autodectection stuff may add additional queries, so you should configure it in the expert settings anyway.

**Comment by xelez** [comment]
@PVince81 I mean, this bug emerged because you had to add 'ipauniqueid' into 2 different arrays.
And original author [have forgotten](https://github.com/owncloud/user_ldap/commit/c47b37e13d76073fc5283fbb6552bf29e72d0022) to add it to the second one.

I think it's a good idea to do something to prevent such errors in the future/ (add comment `// You should probably modify another array <here> as well!` ?)

P.S. Sorry for my English

**Comment by PVince81** [comment]
Ah ok, understood. I wasn't aware that the array was duplicated. Maybe best would be to put it into a constant instead and use it in both locations.

**Comment by jvillafanez** [comment]
👍

**Comment by butonic** [comment]
@PVince81 @jvillafanez unified the code.

**Comment by jvillafanez** [comment]
Nothing wrong with the tests. Either kick it or merge it.

**Comment by jvillafanez** [comment]
Rebased

**Pull request merged**
