### PR TITLE
Include an exact match of the search term for the uuid attribute

### PR DESCRIPTION
**Pull request by jvillafanez**
Fix user:sync by allowing searching by the uuid (exact match)

Note of possible problems if the same attribute is used in the "user search attributes" checkbox

Superseds https://github.com/owncloud/user_ldap/pull/236

### CODE REVIEW

**Comment by tomneedham** [comment]
Motivation / use case here? Is this to improve usability of the single user sync? The admin can add the UUID attribute to the user search attributes to achieve this functionality.

**Comment by jvillafanez** [comment]
I think it's to improve the usability. I'd expect that if I use the -u option to sync only one user by uid, it's should work by default. I find pretty weird that I can't sync one user by uid using the default options, specially when the option clearly specify to use the user id.

**Comment by PVince81** [comment]
discuss and decide whether to keep or close

**Comment by butonic** [comment]
I like the idea, however it adds 'magic' and IMO the proper solution is to properly distinguish username frome userid in core (which we actually started with https://github.com/owncloud/core/pull/32587/files ... it is just that nobody has realized we are doing it as yet another hack)

We should add apis that now allow median searching or exact searching. might be a parameter or a new function.

close and implement https://github.com/owncloud/core/issues/29503#issuecomment-462800169 That will create new apis, then we can revisit this properly.

**Pull request closed without merging**
