### PR TITLE
Backports for 0.15.3 branch

### PR DESCRIPTION
**Pull request by phil-davis**
From PRs:
#639 
#651 
#665

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIUserLDAP-latest-chrome-mysql8.0-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3352/68/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIUserLDAP-master-chrome-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3352/60/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>core-apiAll-21-3-master-mysql8.0-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3354/80/1

**Comment by jnweiger** [comment]
These "backports" won't cause the code to appear in any release. 0.15.4 is already done and publised on Marketplace. Sorry.
If this makes merging into master easier, then let's merge.  of course.

**Comment by phil-davis** [comment]
> These "backports" won't cause the code to appear in any release. 0.15.4 is already done and publised on Marketplace. Sorry.
> If this makes merging into master easier, then let's merge. of course.

It is just to get CI passing so that we can merge-forward.

**Review by jnweiger — APPROVED** [review]
no functional code changes foud. formatting, dronstar, Makefile, and declarations updates only.

**Pull request merged**
