### PR TITLE
Update Screenshot

### PR DESCRIPTION
**Pull request by hurradieweltgehtunter**

### CODE REVIEW

**Comment by mmattel** [comment]
Hello @pmaier1 
Everything is green now.
This is a new logo from marketing, part of the new app logo series.
Mind to approve and merge ?

**Comment by PVince81** [comment]
@davitol I think this wasn't included as it was merged too late

**Comment by PVince81** [comment]
oh, 18 days ago... hmmmm will need to check

**Comment by PVince81** [comment]
from what I see the commit in on the release branch https://github.com/owncloud/user_ldap/commit/92bb58d078c74866227c4dbd7eb2c45c8cd1fc25 and v0.13.0RC1.

Maybe a caching issue on the marketplace side ?

**Comment by davitol** [comment]
I think internal marketplace does not allow .jpg files. Seems it only works with .png images. Public marketplace seems to work fine with .jpg too

**Pull request merged**
