### PR TITLE
Use proxy classes

### PR DESCRIPTION
**Pull request by jvillafanez**
Use the proxy classes instead of the non-proxy ones.

Tests might need adjustment / improvement to use the proxy classes. Other than that I haven't detect any issue.

### CODE REVIEW

**Comment by PVince81** [comment]
At first look looks good, needs testing.

Is it ready for quick testing ? Maybe @cdamken can patch his test setup to test this ?

**Comment by jvillafanez** [comment]
I did some testing and looks fine. It's ready for testing

**Comment by jvillafanez** [comment]
rebased for automatic tests

**Comment by PVince81** [comment]
Code looks good, as discussed 👍

**Pull request merged**
