### PR TITLE
Do not return not availlable users

### PR DESCRIPTION
**Pull request by jvillafanez**
Original PR: https://github.com/owncloud/core/pull/25207 (fix https://github.com/owncloud/core/issues/20588)

### CODE REVIEW

**Comment by PVince81** [comment]
@jvillafanez finish or close ?

**Comment by jvillafanez** [comment]
This needs testing anyway.

**Comment by jvillafanez** [comment]
The LDAP groups can contain any user in the LDAP server. Our app might be interested in some specific users, for example those who start with "a". This implies a user filter such as "(&(objectclass=inetOrgPerson)(cn=a*))".
Without the patch, when ownCloud list the members of a group, it might show users that aren't part of the user filter (those who start with "b"). This is weird because such users aren't known by ownCloud.

I think this patch aims to fix that.

**Comment by tomneedham** [comment]
@jvillafanez @ryno83 can you sign the CLA please?

**Comment by tomneedham** [comment]
@phil-davis good testing scenario here. User listing in groups should build upon the filters already in place for user listing.

**Comment by phil-davis** [comment]
@jvillafanez @tomneedham I noticed this in my list of open PRs where I am mentioned.
Should something happen to this? (resolve conflicts and...)
Should this have the QA-Team label added and get an acceptance test written, or make a separate issue for that, or?

**Comment by tomneedham** [comment]
We can't merge until @ryno83 signs the CLA anyway :/

**Comment by ryno83** [comment]
Signing done ! Sorry for the delay

**Comment by PVince81** [comment]
next up: some conflicts to fix

**Comment by PVince81** [comment]
@jvillafanez please solve the conflicts

**Comment by PVince81** [comment]
and later on @tomneedham please approve the PR, CLA was signed

**Comment by jvillafanez** [comment]
rebased

**Comment by PVince81** [comment]
@jvillafanez please adjust coding standard

**Comment by PVince81** [comment]
fixed the styles

**Comment by PVince81** [comment]
travis is disabled since a long time, ignoring

**Pull request merged**
