### PR TITLE
Do not overwrite quota entries

### PR DESCRIPTION
**Pull request by nfc036**
If a user already has a quota, this value should not be changed to 'default' on a daily basis...

### CODE REVIEW

**Comment by nfc036** [comment]
fixes issue #111

**Comment by nfc036** [comment]
Tests failed, because the mock for IUser is not returning 'default' in getQuota(). As I am not familiar with this project, I am unable to correct the test code.

**Comment by PVince81** [comment]
@jvillafanez "no suitable quota found", isn't that the code path that is never supposed to happen ?

I don't think this fix is correct but if it does work, it might give more clues about the original issue.
The question is why the quota value itself cannot be read in the first place.

**Comment by nfc036** [comment]
user_ldap is not calling getQuota(), but is (currently) updating the quota for every (active) user once a day. There might be better ways to fix this, but the issue is currently a problem for our users/owncloud administrators. Any fix is highly appreciated.

**Comment by PVince81** [comment]
If I understand correctly, you didn't setup any LDAP attributes for quota ? Or the LDAP attribute quota value is empty. In this use case, your PR makes sense, the code should not attempt to set the quota to "default" if there is already a value there.

@jvillafanez please review

**Comment by nfc036** [comment]
Correct, we do not use any LDAP attributes for quotas.

**Comment by jvillafanez** [comment]
We've opted to remove that line for stable 9.1 (still to be merged) https://github.com/owncloud/core/pull/28404 We'll need to port the solution.

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/pull/28404 which existed before.

@nfc036 still, thanks looking into this, at least we know what the solution is to this specific problem.

@jvillafanez let's move forward with the ports

**Pull request closed without merging**
