### PR TITLE
Ignore illegal char when we try to convert the username

### PR DESCRIPTION
**Pull request by jvillafanez**
Fix https://github.com/owncloud/user_ldap/issues/74 as suggested in https://github.com/owncloud/user_ldap/issues/74#issuecomment-298956930

@tomneedham please check this is what you tested.

### CODE REVIEW

**Comment by tomneedham** [comment]
Correct, this should stop `iconv` from returning empty strings

**Comment by tomneedham** [comment]
Tested by carlos 👍

**Comment by PVince81** [comment]
@jvillafanez merge?

**Comment by jvillafanez** [comment]
Rebased. This is ready to be merged (unless CI says otherwise)

**Pull request merged**
