### PR TITLE
Sync should happen in core

### PR DESCRIPTION
**Pull request by tomneedham**

### CODE REVIEW

**Comment by tomneedham** [comment]
Core now takes care of this, after check password the accounts is upserted

**Comment by tomneedham** [comment]
Since we already retrieved the user from LDAP when core does the sync it can use the cached UserEntry

**Comment by tomneedham** [comment]
Note: this would target >10.0.5

**Comment by tomneedham** [comment]
Should this kill setupAccount as well?

**Comment by butonic** [comment]
@tomneedham setupAccount is code in core

**Comment by tomneedham** [comment]
This needs to target the version that https://github.com/owncloud/core/pull/30638/commits is released in (10.0.8)

**Comment by butonic** [comment]
faling stable10 tests until https://github.com/owncloud/core/pull/30638 is merged

**Comment by tomneedham** [comment]
@ownclouders rebase please

**Comment by tomneedham** [comment]
Well, I rebased it

**Comment by tomneedham** [comment]
Just testing this with current stable10 HEAD @ d0ee6a6a403e98a106a61b8f7dfcd06313e0b36c

**Comment by butonic** [comment]
during testing I was worried that we removed the updateGroups call ... turns out the cache for getMemberOf is never read anyway. also, the group backend queries memberof itself and resolves nested groups. Tracking caching of groups and primarygroup in https://github.com/owncloud/user_ldap/issues/226

**Pull request merged**
