### PR TITLE
run core api tests

### PR DESCRIPTION
**Pull request by individual-it**
run API tests of core in an LDAP environment

~~blocked by https://github.com/owncloud/user_ldap/issues/268~~
lets not get blocked, but skip that test https://github.com/owncloud/core/pull/32349

### CODE REVIEW

**Comment by phil-davis** [comment]
``apiShareManagement`` on PHP 5.6 against ``daily-stable10-qa`` got into some problem and reached the 1 hour time limit. I restarted drone.

**Comment by phil-davis** [comment]
On PHP 5.6 ``stable10`` the following suites are taking much longer than on PHP 7.0 ``stable10``:
- ``apiShareManagement```
- ``apiShareOperations``
- ``apiWebdavOperations``
- ``apiWebdavProperties``

Maybe it is just that these are already quite long suites, and everything is slower doing setup/teardown in the LDAP environment, and even slower on PHP 5.6.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/user_ldap/558/435
``apiShareManagement`` on PHP 5.6 took 59 minutes 39 seconds
That is rather close to the 1 hour time limit! We really need to see if something can be done to reduce this to <50 minutes. Otherwise merging this will make unreliable CI.

**Comment by individual-it** [comment]
possibilities:
1. split the suites further
1. mark less tests to be run with LDAP
1. do not run tests on stable10 & PHP 5.6
1. increase timeout

CC @patrickjahns

**Comment by phil-davis** [comment]
I like option 3. We are only 4 months out from the end of PHP 5.6 anyway (and PHP 7.0). We could test only on PHP 7.1

**Comment by individual-it** [comment]
but then we could not test stable10

**Comment by phil-davis** [comment]
I thought stable10 will run fine on PHP 7.1

**Comment by individual-it** [comment]
timeout increased to 120min
@phil-davis please approve

**Comment by individual-it** [comment]
fixes #272

**Pull request merged**
