### PR TITLE
Ldap read range support

### PR DESCRIPTION
**Pull request by jvillafanez**
Original PR: https://github.com/owncloud/core/pull/21525  (Note https://github.com/owncloud/user_ldap/commit/f551110a8dcc7273d83fbf9b86e195a8a36977c0 added to this PR)

### CODE REVIEW

**Comment by PVince81** [comment]
@davitol quick retest ? (you tested the original PR)

Then I think we can merge this :+1:

**Comment by lmctv** [comment]
Just to add that I took a look at the changes, but I cannot help with testing, since in my environment we are using an openldap server, which doesn't support the range syntax in searches.

**Comment by davitol** [comment]
@jvillafanez @PVince81 Smoke tested with several LDAP backends and no problems were found, so I feel OK about merging the PR.  :+1:

BTW, I've tried with an LDAP with 1 million users:

1. Have an LDAP instance with 1M users
2. Go to users page

No users are shown

**Comment by PVince81** [comment]
@jvillafanez backport to 9.1.4, for https://github.com/owncloud/core/issues/20274 ?

**Pull request merged**
