### PR TITLE
Merge back Release 0.15.4

### LINKED ISSUE #605: Release User LDAP 0.15.4
### Reason

- for PR #599 "Fixed read LDAP attribute value 0 returned as null" 
- ... and whatever else has been merged recently:
   -  Security: filter special characters from password field [#636](https://github.com/owncloud/user_ldap/issues/636)
   - LDAP multiple base dns break pagination [#307](https://github.com/owncloud/user_ldap/issues/307)
   - Add warning for disabling email login regarding strict login check [#581](https://github.com/owncloud/user_ldap/issues/581) (Requires 10.5.0)
   - Facelift [#597](https://github.com/owncloud/user_ldap/issues/597)

### Product approval 

- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [x] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" -> https://github.com/owncloud/user_ldap/issues/638
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [ ] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+differences+in+release+process) applies, and adapt this checklist.

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs. -> ttps://github.com/owncloud/docs/issues/3684

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Ping product owner to create github tag for `v${version}-rc1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Manual explorative testing:
    - [x] If this is an enterprise app: Enabling the app must start the grace period
    - [x] If this is the initial release of an app: Check that the minimum version constraint resolves correctly
    - [x] Changelog testing
    - [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries
- [x] Ping `#marketing` channel to coordinate publishing

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10-0)  and [new portal](https://portal.owncloud.com) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [ ] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) is up to date. CREATE NEW FROM #638, deprecate https://github.com/owncloud/qa-enterprise/blob/master/Core/Test_plan_LDAP.md
- [x] Close the testplan issue

### PR DESCRIPTION
**Pull request by jnweiger**
merge back to master, 
closes #605

### CODE REVIEW

**Review by micbar — APPROVED** [review]

**Review by hurradieweltgehtunter — APPROVED** [review]

**Comment by phil-davis** [comment]
https://github.com/owncloud/user_ldap/tree/release-0.15.3
"This branch is 25 commits ahead, 12 commits behind master."

There are things in master that are not in this branch. I will look...

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/user_ldap/3359
CONFLICT (content): Merge conflict in lib/User/Manager.php

I will look for what caused that...

**Review by phil-davis — APPROVED** [review]
IMO CI will pass now.

**Comment by phil-davis** [comment]
@micbar CI should pass in an hour or so. The GitHub settings of this repo make it report "This branch is out-of-date with the base branch". Please override and merge if CI is green.

**Pull request merged**
