### PR TITLE
Easier tls

### PR DESCRIPTION
**Pull request by jvillafanez**
Make it easier to handle TLS support by using a checkbox instead of auto-detection.

Note that the CA certificate for the LDAP server must be accessible by the ownCloud's LDAP library (the default OS' certificate location should work)

Related: https://github.com/owncloud/enterprise/issues/3721

Quick list of changes:
* Add TLS checkbox
* Remove obsolete "detect port" button and TLS auto-detection
* Include operation timeout option to prevent getting stuck if the CA certificate is missing (if TLS checkbox is enabled)

### CODE REVIEW

**Comment by VicDeo** [comment]
Fixes https://github.com/owncloud/user_ldap/issues/505 ?

**Comment by jvillafanez** [comment]
> Fixes #505 ?

Yes, as long as he has the certificates to validate the LDAP server. He can also turn off the certificate validation although it's in the advanced tab.
Maybe we should move that "turn off certificate validation" checkbox....

**Comment by micbar** [comment]
@enbrnz @pako81 @dercorn Please give feedback. There is a recording from JPs demo last friday.

**Comment by pako81** [comment]
@micbar had a look at the code as well as at the demo from JP. Change makes totally sense so 👍

**Comment by micbar** [comment]
@jvillafanez please rebase and merge, seems fine

**Pull request merged**
