### PR TITLE
Fix only seeing one group per LDAP user.

### PR DESCRIPTION
**Pull request by Circuitsoft**
Without this change, each user gets only one LDAP group.

### CODE REVIEW

**Comment by mmattel** [comment]
@jvillafanez @phil-davis adding so this PR can be reviewed

**Comment by jvillafanez** [comment]
Latest master code works without this change.

Screenshot from 2020-02-18 14-30-38

Screenshot from 2020-02-18 14-31-00

There are no steps to reproduce nor setup to check, so I just checked the basic scenario we have for LDAP.
In addition, just setting a limit of 1000 groups isn't a good solution. What if there are 2000 groups? what if the a user is a member of 2000 groups?

Unless I'm missing something, I vote for closing.

**Comment by mmattel** [comment]
Thanks for this analysis and feedback. Agree to close this PR.

**Comment by phil-davis** [comment]
@Circuitsoft any feedback on the comments above?
Or can you give more information about reproducing the problem that you are fixing?

**Comment by Circuitsoft** [comment]
Using Samba 4.9.5 as the LDAP server, it seems that an "unlimited" request stops after 1 group.

**Comment by jvillafanez** [comment]
As far as I know, Samba uses an "Active Directory-like", so nested groups are expected there. Please, make sure you have that checkbox active in the configuration (advanced tab -> directory settings -> nested groups)

**Comment by DeepDiver1975** [comment]
old -> dead -> close

**Pull request closed without merging**
