### PR TITLE
Only use IndexIgnore if mod_autoindex.c is enabled/loaded

### PR DESCRIPTION
**Pull request by kdslkdsaldsal**
Same as https://github.com/owncloud/core/issues/28343

Ref: https://github.com/owncloud/core/issues/28307

### CODE REVIEW

**Comment by tomneedham** [comment]
Hey @kdslkdsaldsal can you rebase, then we can get this merged in :)

**Comment by kdslkdsaldsal** [comment]
@tomneedham Done

**Comment by tomneedham** [comment]
Thanks @kdslkdsaldsal !

**Comment by kdslkdsaldsal** [comment]
Backports to stable9.1 and 9 in https://github.com/owncloud/core/issues/28592 and https://github.com/owncloud/core/issues/28593

**Pull request merged**
