### PR TITLE
Adjust unittest for new core code

### PR DESCRIPTION
**Pull request by jvillafanez**
Fix https://github.com/owncloud/user_ldap/issues/66

Open to improvements

### CODE REVIEW

**Comment by jvillafanez** [comment]
@SergioBertolinSG could you check the integration tests and update the PR accordingly?

**Comment by SergioBertolinSG** [comment]
In the IntegrationTestUserAvatar.php, if I add

```php
\OC_User::setUserId($username);
		$userObject = \OC::$server->getUserManager()->get($username);
		if (!is_null($userObject)) {
			$userObject->updateLastLoginTimestamp();
		}
		\OC_Util::setupFS($username);
		if (\OC_User::userExists($username)) {
			\OC::$server->getUserFolder($username);
		}
```

in execFetchTest, it doesn't fail when using getUserFolder.

But it fails eventually in 
```php
\OC::$server->getAvatarManager()->getAvatar($username)->exists()
```

This trick doesn't works at all in IntegrationTestUserDisplayName.php,

It is failing here \OC::$server->getUserManager()->get($username)->getDisplayName()



@DeepDiver1975 seems to be related with account table, any suggestions?

**Comment by DeepDiver1975** [comment]
> \OC::$server->getUserManager()->get($username)->getDisplayName()

if it fails here the user is not know to the accounts table. to get the user in: login once

**Comment by SergioBertolinSG** [comment]
OK I am trying to add 

$userSession = \OC::$server->getUserSession();
$userSession->login($username, $username);

in case1 of IntegrationTestUserDisplayName, no luck.

**Comment by jvillafanez** [comment]
Test looks fine, but phpunit seems to crash with php 7.1 trying to generate the clover report 😕

**Comment by DeepDiver1975** [comment]
disablecoverage then for 7.1 - thx

**Comment by DeepDiver1975** [comment]
nice - thx

**Pull request merged**
