### PR TITLE
change color of warning sign

### PR DESCRIPTION
**Pull request by hurradieweltgehtunter**
In adtion to #672 

grafik

### CODE REVIEW

**Review by mmattel — APPROVED** [review]
LGTM
The use of orange makes it better differenciateable from the red error block.

**Comment by jnweiger** [comment]
As an average admin, I would not know the specific use of orange here. 

The meaning here is "Everything is currently fine, but be cautious, when you enter these tabs"
It is easily misunderstood as "Something needs your attention in this tab"

WND e.g. also uses orange in the admin interface -- there it means again something different (and non-guessable)

Sorry for lobbying against this feature. I still fail to see a usecase that would outweight the possible confusion, that I can imagine.

**Comment by voroyam** [comment]
> As an average admin, I would not know the specific use of orange here. 
> 
> 
> 
> The meaning here is "Everything is currently fine, but be cautious, when you enter these tabs"
> 
> It is easily misunderstood as "Something needs your attention in this tab"
> 
> 
> 
> WND e.g. also uses orange in the admin interface -- there it means again something different (and non-guessable)
> 
> 
> 
> Sorry for lobbying against this feature. I still fail to see a usecase that would outweight the possible confusion, that I can imagine.

Total agree.

**Comment by hurradieweltgehtunter** [comment]
I happily do another change if you let me know how it should be

**Comment by voroyam** [comment]
My view has not changed - remove the warning sign all together. The reasoning behind my view I described in a comment above.

**Pull request merged**
