### PR TITLE
[Tests-Only][full-ci] enforce strict type checking in acceptace tests code

### PR DESCRIPTION
**Pull request by dpakach**
Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code

**note** this PR was generated by a automated script

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiUserLDAP-latest-postgres9.4-php7.3</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3601/38/1

**Comment by individual-it** [comment]
CI failed in a clone step, restarted

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIUserLDAP-master-chrome-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3602/54/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiUserLDAPS-master-mysql8.0-php7.3</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3603/42/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIUserLDAP-latest-chrome-oracle-php7.3</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3602/63/1

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
