### PR TITLE
[tests-only] skip dbConversion tests

### PR DESCRIPTION
**Pull request by phil-davis**
Those need special setup, which is done in core. We don't need to run those in app test pipelines.

### CODE REVIEW

**Review by individual-it — APPROVED** [review]

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/user_ldap/ - drone did not start or give an error???

I will force-push again.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>core-apiAll-21-10-master-mysql8.0-php7.3</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3669/80/1

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/user_ldap/3669/80/18
`apiSharePublicLink2/copyFromPublicLinkOc10Issue37683.feature:9` failed - issue https://github.com/owncloud/user_ldap/issues/702

We can't get green CI until that issue is also sorted out.

**Comment by phil-davis** [comment]
@micbar this fixes one CI problem. It would be nice to be able to merge this, and issue #702 can be looked at separately.
Please force-merge if you can.

**Pull request merged**
