### PR TITLE
Just strip "low" chars, but don't do anything else

### PR DESCRIPTION
**Pull request by jvillafanez**
For testing purposes:
```
// $b contains all ascii chars from 0-255
php > var_dump(filter_var($b, FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW));
string(229) " !&#34;#$%&&#39;()*+,-./0123456789:;?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~��������������������������������������������������������������������������������������������������������������������������������"
php > var_dump(filter_var($b, FILTER_UNSAFE_RAW, FILTER_FLAG_STRIP_LOW));
string(224) " !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~��������������������������������������������������������������������������������������������������������������������������������"
```

### CODE REVIEW

**Comment by jvillafanez** [comment]
Linking with https://github.com/owncloud/user_ldap/issues/661 and https://github.com/owncloud/user_ldap/issues/662

**Review by jnweiger — COMMENTED** [review]
Interesting, that we filter characters at all. 
Should't we just keep any chars as they are? We don't control, what weird password patterns people have in their ldap. 
E.g. is a TAB character legal?

**Comment by jvillafanez** [comment]
Original PR is https://github.com/owncloud/user_ldap/pull/636 . I'll leave the decision to the security experts.

**Comment by JanAckermann** [comment]
>E.g. is a TAB character legal?
With this PR it is not possible to have a TAB in the password, this needs to be checked.

But keep nullbyte injections in mind, if you decide to remove the filter

**Comment by cdamken** [comment]
> With this PR it is not possible to have a TAB in the password, this needs to be checked.

Is allowed to `type` tabs?

**Comment by phil-davis** [comment]
It is difficult for a user to "insert" a tab into their password, because if they press the tab key in password input fields then the focus jumps out of the field to the next field. But it can be done if the user is "clever" and copies a tab character from some other place and pastes it into the password field.

Is there a "standard" somewhere that says what characters are supposed to be allowed/not allowed in a "standard" password?

**Comment by jnweiger** [comment]
> Is there a "standard" somewhere that says what characters are supposed to be allowed/not allowed in a "standard" password?

It is most likely each LDAP Admin's discretion to allow / forbid / enforce certain character ranges. Not our call to divert.
As a user who has to type passwords while watched by strangers, I'd be happy for everything invisible.

**Comment by IljaN** [comment]
> Is there a "standard" somewhere that says what characters are supposed to be allowed/not allowed in a "standard" password?

From what I know best practices are to allow everything as password. Tough I don't know if this rule includes non-printable characters. I guess not but needs to be researched ;)

**Comment by phil-davis** [comment]
The original issue talked about making sure that carriage-return and line-feed characters were not "injected" into a password.
Maybe we should only strip those from the password string, and leave other "extra-special" characters like tab, backspace, escape, and the other "special binary values below ASCII %x20"

**Comment by C0rby** [comment]
> > Is there a "standard" somewhere that says what characters are supposed to be allowed/not allowed in a "standard" password?
> 
> From what I know best practices are to allow everything as password. Tough I don't know if this rule includes non-printable characters. I guess not, but needs to be researched ;)

I think we can safely disallow/strip non printable characters from the password because I don't think there is a way a normal user would be able to get them into the password field.
Also I think the most used password mangers won't generate passwords with non-printable characters but I could be wrong on this point.

**Review by IljaN — APPROVED** [review]

**Comment by voroyam** [comment]
> For testing purposes:
> 
> ```
> // $b contains all ascii chars from 0-255
> php > var_dump(filter_var($b, FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW));
> string(229) " !&#34;#$%&&#39;()*+,-./0123456789:;?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~��������������������������������������������������������������������������������������������������������������������������������"
> php > var_dump(filter_var($b, FILTER_UNSAFE_RAW, FILTER_FLAG_STRIP_LOW));
> string(224) " !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~��������������������������������������������������������������������������������������������������������������������������������"
> ```

can you tell me what characters are allowed as per this PR and what are not allowed? I can't figure out what output is the legal and what is the illegal one.

**Comment by voroyam** [comment]
simple language please :)

**Comment by voroyam** [comment]
So everything that is not blacked out by my huge black bar is a legal password character? 

image

**Comment by phil-davis** [comment]
https://www.asciitable.com/

Yes, the codes from 0 to 31 are "non-printable" things like null, backspace, tab, line-feed, carriage-return, escape and stranger codes for things that are never used by ordinary mortals. Those cannot be used in a password.

**Comment by voroyam** [comment]
Okay, this is something my limited brain can understand. Thanks. 

Can you please tell me now the difference in the amount of legal characters between this PR and https://github.com/owncloud/user_ldap/pull/636?

**Comment by phil-davis** [comment]
`FILTER_SANITIZE_STRING` in the other PR also removes things that look like HTML tags. Example:
```
$x = "<b>test</b>/best";
$y = \filter_var($x, FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW);
echo $y;
```

The output is:
```
test/best
```

Notice that sequences like `<b>` and `</b>` are removed. So all sorts of characters can be removed if they occur between `<>`. But the `/b` in `/best` is not removed - it is not between `<>`.

So "it's complicated" - it is HTML tag patterns that were being removed. Passwords containing `<` and `>` would certainly have been changed.

**Pull request merged**
