### PR TITLE
Added missing core suites

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
Added missing core suites in user_ldap acceptance tests suites

## Related Issue
https://github.com/owncloud/user_ldap/issues/503

## How Has This Been Tested?

- :robot:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
@kiranparajuli589 the `.drone.yml` contains some duplicate stuff.
Do:
```
drone starlark --source .drone.starlark
```
and commit/squash/force push.
Then drone should start.

**Comment by phil-davis** [comment]
I restarted drone again just now. It had stupid Oracle 10-minute timeouts.

**Comment by kiranparajuli589** [comment]
> I restarted drone again just now. It had stupid Oracle 10-minute timeouts.
> 
> Note: this might have a problem because we have just split core `apiWebdavMove` suite in core. So we might also have to make that change here in this `user_ldap` PR.

Then, I can close this PR, finish splitting, then open this again!
@phil-davis what do you suggest?

**Comment by phil-davis** [comment]
Keep the PR here, and when the core suite splitting is  finished merging later today, make the needed changes here. And hopefully I can merge it tonight.

**Comment by phil-davis** [comment]
Needs CI to be run again after all the core suite-splitting has been merged.

**Pull request merged**
