### PR TITLE
[full-ci] Do not check for the username if if has been processed already

### PR DESCRIPTION
**Pull request by jvillafanez**
Targets https://github.com/owncloud/core/pull/39105
Changes are backwards-compatible, so https://github.com/owncloud/core/pull/39105 isn't a real requirement, but this PR won't do anything without it.

### CODE REVIEW

**Comment by JanAckermann** [comment]
@jvillafanez you might want to rebase master ?

**Comment by jvillafanez** [comment]
@phil-davis any idea of what could be happening?
I think we should remove the log check from the tests. If Alice is a local user, ownCloud shouldn't contact with LDAP any longer, so the log entry shouldn't appear. The entry showing in the logs could be from a previous test.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiUserLDAP-master-postgres9.4-php7.3</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3736/32/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiUserLDAP-master-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/4190/28

**Comment by pako81** [comment]
do we want to have this in 0.17.0?

**Comment by jvillafanez** [comment]
If it doesn't give any problems, I think so. I just bumped into this again recently: login with the admin took a lot of time because the ldap server was disconnected, which seems bad. Anyway, I don't think it's a priority.

**Comment by pako81** [comment]
Got it. If we can have it, even better.

**Comment by jvillafanez** [comment]
I suspect the failure comes from the logs, because the test expects an error that doesn't happen any longer. Not sure who can confirm this.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/user_ldap/4390/29/13
```
runsh: Total unexpected failed scenarios throughout the test run:
apiUserLDAP/serverConnection.feature:48
```

```
  Scenario: authentication does not work when the hostname contains a wrong protocol             # /var/www/owncloud/testrunner/apps/user_ldap/tests/acceptance/features/apiUserLDAP/serverConnection.feature:48
    Given LDAP config "LDAPTestId" has key "ldapHost" set to "http://%ldap_host_without_scheme%" # UserLdapGeneralContext::ldapConfigHasKeySetTo()
    When user "Alice" requests "/index.php/apps/files" with "GET" using basic auth               # AuthContext::userRequestsURLWithUsingBasicAuth()
    Then the HTTP status code should be "401"                                                    # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the last lines of the log file should contain log-entries containing these attributes:   # LoggingContext::theLastLinesOfTheLogFileShouldContainEntriesWithTheseAttributes()
      | app | message                                                                              |
      | PHP | ldap_connect(): Could not create session handle: Bad parameter to an ldap routine at |
      | PHP | ldap_set_option(): supplied argument is not a valid ldap link resource at            |
      log entry:
      {"reqId":"AmcK0v6TNog2YKjXnJzG","level":3,"time":"2023-02-24T02:08:42+00:00","remoteAddr":"192.168.30.6","user":"--","app":"PHP","method":"GET","url":"\/index.php\/apps\/files","message":"ldap_set_option(): supplied argument is not a valid ldap link resource at \/var\/www\/owncloud\/server\/apps\/user_ldap\/lib\/LDAP.php#296"}

      Failed asserting that 'ldap_set_option(): supplied argument is not a valid ldap link resource at /var/www/owncloud/server/apps/user_ldap/lib/LDAP.php#296' contains "ldap_connect(): Could not create session handle: Bad parameter to an ldap routine at".
```

I will have a look...

**Comment by phil-davis** [comment]
I removed one of the log file checks in the failing test. The `ldap_connect()` error message does not happen any longer.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/user_ldap/4391/29/12

```
    And the last lines of the log file should contain log-entries containing these attributes:   # LoggingContext::theLastLinesOfTheLogFileShouldContainEntriesWithTheseAttributes()
      | app | message                                                                   |
      | PHP | ldap_set_option(): supplied argument is not a valid ldap link resource at |
      log entry:
      {"reqId":"mifRRq5OUjjbqWcqgQT5","level":2,"time":"2023-02-24T08:39:56+00:00","remoteAddr":"192.168.45.6","user":"--","app":"core","method":"GET","url":"\/index.php\/apps\/files","message":"Login failed: 'Alice' (Remote IP: '192.168.45.6')"}
      
      Failed asserting that 'core' contains "PHP".
```

I don't think that trying to check the detail of the log output in the test is doing anything really useful.
The existing check for HTTP status `401` "unauthorized" seems enough to me.

**Pull request merged**
