### PR TITLE
[tests-only] Use owncloudci/wait-for docker image

### PR DESCRIPTION
**Pull request by phil-davis**
Update the drone starlark code the same as https://github.com/owncloud/activity/pull/1036

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>core-cliAll-2-1-master-mysql8.0-php7.3</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3652/92/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>core-cliAll-2-1-master-mysql8.0-php7.3</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3653/92/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>core-cliAll-2-1-master-mysql8.0-php7.3</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3654/92/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>core-cliAll-2-1-master-mysql8.0-php7.3</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3655/92/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>core-cliAll-2-1-master-mysql8.0-php7.3</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/user_ldap/3658/92/1

**Review by kiranparajuli589 — APPROVED** [review]

**Pull request merged**
