### PR TITLE
fix bind

### PR DESCRIPTION
**Pull request by butonic**
otherwise the password is irrelevant

### CODE REVIEW

**Comment by butonic** [comment]
introduced with https://github.com/owncloud/user_ldap/pull/138

**Comment by jvillafanez** [comment]
Is `OC\ServerNotAvailableException` actively used in core? Ideally, there should be a ldap's `ServerNotAvailableException`, which inherits from a ldap's `ConnectionException`. The `BindFailedException` should also inherit from the `ConnectionException`.
Conversions to ownCloud's exceptions might be required, but they should be converted near the junction with the ownCloud's code.

**Comment by butonic** [comment]
Yes, `OC\ServerNotAvailableException` is basically used in core to immediately kill the request and log the error.

**Comment by tomneedham** [comment]
https://github.com/owncloud/user_ldap/pull/149 was already fixed and merged. @patrickjahns Do we merge release back into master when its done - ie. can we close this and the fixes from the release branch will make it here?

**Comment by patrickjahns** [comment]
@tomneedham 
After the release, a release branch "flows back" to the development branch.
We can backport the changes (if required) into the development branch

**Pull request closed without merging**
