### PR TITLE
No avatar DI

### PR DESCRIPTION
**Pull request by butonic**
fixes a listing group shares when ldap and encryption are used

### CODE REVIEW

**Comment by PVince81** [comment]
Approach sounds good. @jvillafanez please review in detail

**Comment by jvillafanez** [comment]
I won't complain if this is needed for other ownCloud versions, but the solution itself is quite bad.

**Comment by butonic** [comment]
Indeed. Basically a quickfix that we can release without having to QA and release a new version of core. The proper fix is to move avatar sync to core. tracked in https://github.com/owncloud/core/issues/30840

**Comment by cdamken** [comment]
@butonic Can I add the QA Label in both issues?

**Comment by tomneedham** [comment]
Core fix implemented instead - this isn't required https://github.com/owncloud/core/pull/30810

**Pull request closed without merging**
