### PR TITLE
Allow plus in LDAP usernames

### PR DESCRIPTION
**Pull request by phil-davis**
core PR https://github.com/owncloud/core/pull/36613 proposes allowing `+` in usernames.

If that PR is accepted, then we should/could also allow `+` in usernames coming from LDAP.

This PR implements that, and adds unit tests to check the LDAP `sanitizeUsername()` method. (There were not any tests for that yet)

- [x] set minimum core version to 10.4 (we only want to allow sync of LDAP usernames containing `+` if core also supports usernames containing `+`)

IMO this should only be merged and released after core 10.4 has been released.

### CODE REVIEW

**Comment by phil-davis** [comment]
@pako81 this would also be needed if we start allowing `+` in usernames/UIDs

**Comment by pako81** [comment]
@phil-davis makes sense 👍

**Comment by phil-davis** [comment]
CI here is "stuck" - with core min version 10.4 we cannot have test pipelines against latest.
But there is no rush - we can run CI again when core 10.4 is latest.

**Comment by mmattel** [comment]
@phil-davis has there anything changed that allows a progress 😅

**Comment by phil-davis** [comment]
I rebased to catch up with current user_ldap.

There is no point releasing this anyway, until core 10.4 is out. So we can easily merge this the day that 10.4 community release happens and release user_ldap soon after.

**Comment by phil-davis** [comment]
@micbar @HanaGemela what do you want to do about this PR?

I could adjust the CI here so it does not test against `latest` and bumps core min-version to 10.4. Then CI will pass and we could merge it and prepare the app release before official core 10.4 release - like we are doing for various other apps.

**Comment by micbar** [comment]
@phil-davis Does it really have a strickt dependency? what would happen, if I use the current version with 10.4.0?

**Comment by phil-davis** [comment]
If your LDAP does not actually have any usernames containing `+` then yes, it should still work on a core 10.2 or 10.3 system.

Do you want to try and keep the new version of user_ldap installable on 10.2 and 10.3?

**Comment by phil-davis** [comment]
Note: if we wait until core 10.4.0 becomes the "latest" community tarball, then I can remove the last commit from this PR.

**Comment by phil-davis** [comment]
> Note: if we wait until core 10.4.0 becomes the "latest" community tarball, then I can remove the last commit from this PR.

10.4.0 is now "latest". I reverted the 3rd commit. Let's see what happens to CI.

**Comment by mmattel** [comment]
Green, green :smile:

**Comment by phil-davis** [comment]
@micbar please get a review of this.

**Pull request merged**
