### PR TITLE
delete unneeded mailhog url

### PR DESCRIPTION
**Pull request by individual-it**
we don't need that mailhogUrl setting any-more
see owncloud/core#31079

### CODE REVIEW

**Comment by individual-it** [comment]
CI fails because backport of change in core was only merged this morning, should work tomorrow

**Comment by tomneedham** [comment]
planned - because we want to keep the release really small and focused with just the sync changes

**Comment by phil-davis** [comment]
@tomneedham this is essential to make the CI pass because of existing acceptance test infrastructure changes in core. It is not a change to any released code.

**Comment by tomneedham** [comment]
Cool - sorry! You guys decide on this and merge as necessary :)

**Pull request merged**
