### PR TITLE
Add apiAuth core acceptance test suite

### PR DESCRIPTION
**Pull request by phil-davis**
Issue #380

### CODE REVIEW

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by individual-it** [comment]
blocked by https://github.com/owncloud/user_ldap/issues/383 waiting for new QA build

**Pull request merged**
