### PR TITLE
Harden empty

### PR DESCRIPTION
**Pull request by VicDeo**
Ported and squashed https://github.com/owncloud/core/pull/25689

### CODE REVIEW

**Comment by VicDeo** [comment]
@DeepDiver1975 @butonic

**Comment by DeepDiver1975** [comment]
@vicdeo mind having a look at travis? THX

**Comment by DeepDiver1975** [comment]
And also sign the cla please - thx

**Comment by VicDeo** [comment]
@DeepDiver1975 signed. 
There are no errors on Travis but  116 deprecation warnings from PHPUnit

**Comment by DeepDiver1975** [comment]
Warnings are displayed on all versions - with 5.6 the phpunit process seems to exit with a different exit code.

Anyway - please fix the warnings while at it .... THX

**Comment by VicDeo** [comment]
@DeepDiver1975 Done

**Comment by DeepDiver1975** [comment]
Nice! Thx

**Comment by butonic** [comment]
- [x] wizard with 2 ldap servers
- [x] login / logout
- [x] user listing with uid as UUID and internal user attribute

👍 nice!

**Pull request merged**
