### PR TITLE
Include "memberOf"-based algorithms to find users within groups

### PR DESCRIPTION
**Pull request by jvillafanez**
Add a couple of algorithms to get the members of the groups based on the "memberOf" attribute. The algorithms have some requirements so not all of them could be used in a specific situation.
The "groupScan" is the default one, which has been used until now. It can be used as a fallback if not any of the rest fits.

### CODE REVIEW

**Comment by jnweiger** [comment]
I am happy to include this in the 0.16.0 release, if it can be merged within the next two days. Please redirect this pr to the release-0.16.0 branch then.

**Comment by jnweiger** [comment]
@jvillafanez Please redirect to release-0.16.0 branch for inclusion in server 10.9.0

**Comment by jvillafanez** [comment]
Cherry-picked to https://github.com/owncloud/user_ldap/pull/697 for the release. We can close this and merge the 697 one

**Review by JanAckermann — APPROVED** [review]

**Comment by jvillafanez** [comment]
Closing since the code has been moved to the release branch (https://github.com/owncloud/user_ldap/pull/697). The release branch will eventually be merged into master.

**Pull request closed without merging**
