### PR TITLE
Add network timeout

### PR DESCRIPTION
**Pull request by tomneedham**
Fixes https://github.com/owncloud/user_ldap/issues/320

### CODE REVIEW

**Comment by PVince81** [comment]
@jvillafanez please review / take over

**Comment by jvillafanez** [comment]
Do we want to make this option configurable? Other than that, code looks fine.

**Comment by PVince81** [comment]
configurable makes sense, yes

@jvillafanez please make it so

not sure where the other settings are, config.php or oc_appconfig

**Comment by PVince81** [comment]
I didn't expect a GUI setting, but ok. Good.

**Comment by PVince81** [comment]
well, after tests pass

**Comment by jvillafanez** [comment]
I think the test failing are for the webUI, maybe a too strict test...
Maybe @phil-davis or @individual-it can have a look since they'll probably know where to look at faster.

I'll check tomorrow what's happening.

**Comment by individual-it** [comment]
@jvillafanez looks like the issue that was introduced by https://github.com/owncloud/core/pull/34333 It was reverted yesterday and a new QA tarball should have been build. Please rerun tests and ping me if you still have problems

**Comment by PVince81** [comment]
"Failed to restart your build". It's not even **my** build!

**Comment by jvillafanez** [comment]
Fixed

**Comment by PVince81** [comment]
thanks!

**Pull request merged**
