### PR TITLE
Add groupOfUniqueNames to the group list

### PR DESCRIPTION
**Pull request by pboyd04**
If you use LDAP with group OfUniqueNames instead of groupOfNames for group lists they don't show up in the wizard. This fixes that and makes it much easier for a user to setup in this situation.

### CODE REVIEW

**Comment by tomneedham** [comment]
Hey @pboyd04 thanks for the PR. Do you mind rebasing this? And @jvillafanez could you review this? Thanks :)

**Comment by jvillafanez** [comment]
@pboyd04 in the `determineGroupObjectClasses` function you should probably add the item as well. I think that's the only thing missing. For the rest, it's fine.

**Comment by pboyd04** [comment]
That function already has * in the object class list. So I'm not sure it really needs it.

**Comment by jvillafanez** [comment]
I'm not sure if it's required, but it should be there.

**Comment by pboyd04** [comment]
Ok, done.

**Pull request merged**
