### PR TITLE
Use new settings registration method.

### PR DESCRIPTION
**Pull request by tomneedham**
Fixes https://github.com/owncloud/user_ldap/issues/52

### CODE REVIEW

**Comment by PVince81** [comment]
I don't think "Authentication" is the correct term here. LDAP is not only used for authentication for also for sharing if you specify groups.
Not sure what would fit better:
- User backend
- User sources
- User providers
- ???

@jvillafanez any better ideas ?

**Comment by PVince81** [comment]
Also maybe use a person icon instead of cog ?

**Comment by PVince81** [comment]
Otherwise it looks good. The wizard works.

A small little detail: when enabling the LDAP app from the apps page, the "Authentication" section doesn't appear automatically. I need to refresh the page. Solving this is probably not that easy.

**Comment by jvillafanez** [comment]
"User backends" sounds more technical. I'd choose "user providers".

**Comment by tomneedham** [comment]
https://github.com/owncloud/core/pull/27296#issue-211383466 adds the icon for the 'authentication' panel. 'User Providers' it is then?

**Comment by tomneedham** [comment]
> A small little detail: when enabling the LDAP app from the apps page, the "Authentication" section doesn't appear automatically. I need to refresh the page. Solving this is probably not that easy.

Correct. When we ajax-ify it all we can refresh the sections probably quite easily.

**Comment by DeepDiver1975** [comment]
Generally speaking this works - anything else can be adjusted later :+1:

**Pull request merged**
